# Generated by Django 2.2.14 on 2020-07-07 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20200615_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Адрес и дом')),
                ('delivery_address_house_part', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Подъезд')),
                ('delivery_apart', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Квартира / Офис')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(default=None, max_length=15, null=True, verbose_name='Номер телефона')),
                ('order_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
