# Generated by Django 2.2.14 on 2020-07-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='no_image_given_128_128.jpg', null=True, upload_to=''),
        ),
    ]
