# Generated by Django 2.2.14 on 2020-07-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='no_image_given_128_128.jpg', height_field=128, null=True, upload_to='', width_field=128),
        ),
    ]
